ALTER TABLE punches ADD COLUMN IF NOT EXISTS extra_ot_minutes INTEGER;
ALTER TABLE punches ADD COLUMN IF NOT EXISTS extra_ot_granted_by VARCHAR;
ALTER TABLE punches ADD COLUMN IF NOT EXISTS extra_ot_granted_at TIMESTAMP;

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS shift_type VARCHAR NOT NULL DEFAULT 'regular';
